// <auto-generated />
namespace BolyaiClubWindowsFormsApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenterChangedToClient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenterChangedToClient));
        
        string IMigrationMetadata.Id
        {
            get { return "201505240907353_RenterChangedToClient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
